In [1]:
pwd

'/Users/jangregrowicz'

In [2]:
cd git/bootcamp/

/Users/jangregrowicz/git/bootcamp


In [3]:
import numpy as np

In [4]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
my_arr = np.array([1, 2, 3, 4])

In [6]:
type(my_arr)

numpy.ndarray

In [7]:
my_arr.dtype

dtype('int64')

In [8]:
my_arr.shape

(4,)

In [9]:
my_arr.astype(float)

array([1., 2., 3., 4.])

In [10]:
my_arr.mean()

2.5

In [11]:
my_arr.std()

1.118033988749895

In [12]:
np.sum(my_arr)

10

In [13]:
n = 10
np.zeros(n)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
my_arr = np.ones(n)
my_fives = my_arr * 5


In [20]:
np.zeros_like(my_fives)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
my_arr = np.array([1,2,3,4,5])

np.exp(my_arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [24]:
my_arr = np.arange(1, 6)

In [25]:
np.dot(my_arr, my_arr)

55

In [26]:
np.pi

3.141592653589793

In [27]:
import scipy.special

In [28]:
scipy.special.erf(my_arr)

array([0.84270079, 0.99532227, 0.99997791, 0.99999998, 1.        ])

In [31]:
import scipy.stats

In [45]:
def multiply_python(arr):
    new_arr = np.zeros_like(arr)
    
    for i, value in enumerate(arr):
        new_arr[i] = value * 2
    return new_arr

In [46]:
my_arr = np.arange(1000)

In [49]:
%timeit multiply_python(my_arr)

350 µs ± 14.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [51]:
%timeit my_arr * 2

1.49 µs ± 26.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
